# Default values for kn-api-server-source.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespaces:
  - namespace: "api-server-source"
    roleName: "kn-role"
    roleBindingName: "kn-role-binding"
    serviceAccount: "kn-service-account"
  - namespace: "test"
    roleName: "kn-role"
    roleBindingName: "kn-role-binding"
    serviceAccount: "kn-service-account"
    watch: true

roleRules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch


sinkName: "event-display"

apiServerSourceName: "api-server-source"
apiServerSourceNs: "api-server-source"
apiServerSourceSA: "kn-service-account"
apiServerSourceMode: "Resource"
