apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  name: {{ .Values.apiServerSourceName }}
  namespace: {{ .Values.apiServerSourceNs }}
spec:
  serviceAccountName: {{ .Values.apiServerSourceSA }}
  mode: {{ .Values.apiServerSourceMode }}
  resources:
    - apiVersion: v1
      kind: Event
  namespaceSelector:
    matchLabels:
      kubearchive: "watch"
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: {{ .Values.sinkName }}
