{{- /*
apply the role to all namespaces
*/ -}}
{{- range .Values.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .roleName }}
  namespace: {{ .namespace }}
rules: 
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
{{- end }}
