apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.roleName }}
  namespace: {{ .Values.apiServerSourceNs }}
rules: 
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
