apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.roleBindingName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.roleName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.apiServerSourceSA }}
  namespace: {{ .Values.apiServerSourceNs }}
